export enum CATEGORY_KEYS {
  GET_CATEGORIES = 'GET_CATEGORIES',
  GET_CATEGORY_BY_ID = 'GET_CATEGORY_BY_ID',
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORIES = 'DELETE_CATEGORIES',
  COUNT_PRODUCTS_BY_CATEGORY = 'COUNT_PRODUCTS_BY_CATEGORY',
}
